/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTrendsRouteImport } from './routes/dashboard/trends'
import { Route as DashboardTimelineRouteImport } from './routes/dashboard/timeline'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard/records'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardChartsRouteImport } from './routes/dashboard/charts'
import { Route as DashboardRecordsRecordIdRouteImport } from './routes/dashboard/records/$recordId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrendsRoute = DashboardTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimelineRoute = DashboardTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChartsRoute = DashboardChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRecordIdRoute =
  DashboardRecordsRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => DashboardRecordsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/charts': typeof DashboardChartsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/records': typeof DashboardRecordsRouteWithChildren
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/records/$recordId': typeof DashboardRecordsRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/charts': typeof DashboardChartsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/records': typeof DashboardRecordsRouteWithChildren
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/records/$recordId': typeof DashboardRecordsRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/charts': typeof DashboardChartsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/records': typeof DashboardRecordsRouteWithChildren
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/records/$recordId': typeof DashboardRecordsRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/charts'
    | '/dashboard/chat'
    | '/dashboard/records'
    | '/dashboard/timeline'
    | '/dashboard/trends'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/records/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/charts'
    | '/dashboard/chat'
    | '/dashboard/records'
    | '/dashboard/timeline'
    | '/dashboard/trends'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/records/$recordId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/charts'
    | '/dashboard/chat'
    | '/dashboard/records'
    | '/dashboard/timeline'
    | '/dashboard/trends'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/records/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trends': {
      id: '/dashboard/trends'
      path: '/trends'
      fullPath: '/dashboard/trends'
      preLoaderRoute: typeof DashboardTrendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timeline': {
      id: '/dashboard/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardTimelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/charts': {
      id: '/dashboard/charts'
      path: '/charts'
      fullPath: '/dashboard/charts'
      preLoaderRoute: typeof DashboardChartsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records/$recordId': {
      id: '/dashboard/records/$recordId'
      path: '/$recordId'
      fullPath: '/dashboard/records/$recordId'
      preLoaderRoute: typeof DashboardRecordsRecordIdRouteImport
      parentRoute: typeof DashboardRecordsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRecordsRouteChildren {
  DashboardRecordsRecordIdRoute: typeof DashboardRecordsRecordIdRoute
}

const DashboardRecordsRouteChildren: DashboardRecordsRouteChildren = {
  DashboardRecordsRecordIdRoute: DashboardRecordsRecordIdRoute,
}

const DashboardRecordsRouteWithChildren =
  DashboardRecordsRoute._addFileChildren(DashboardRecordsRouteChildren)

interface DashboardRouteChildren {
  DashboardChartsRoute: typeof DashboardChartsRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardRecordsRoute: typeof DashboardRecordsRouteWithChildren
  DashboardTimelineRoute: typeof DashboardTimelineRoute
  DashboardTrendsRoute: typeof DashboardTrendsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChartsRoute: DashboardChartsRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardRecordsRoute: DashboardRecordsRouteWithChildren,
  DashboardTimelineRoute: DashboardTimelineRoute,
  DashboardTrendsRoute: DashboardTrendsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
