"""Sync chat models

Revision ID: 1815ea57ea3f
Revises: 42c516012fa0
Create Date: 2026-02-19 12:14:59.674535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1815ea57ea3f'
down_revision: Union[str, Sequence[str], None] = '42c516012fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_provider')
    op.add_column('chat_message', sa.Column('session_id', sa.Uuid(), nullable=False))
    op.add_column('chat_message', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chat_message', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'chat_message', 'chat_session', ['session_id'], ['id'])
    op.drop_column('chat_message', 'mem0_memory_ids')
    op.drop_column('chat_message', 'user_message')
    op.drop_column('chat_message', 'context_used')
    op.drop_column('chat_message', 'assistant_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('assistant_message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat_message', sa.Column('context_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('chat_message', sa.Column('user_message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat_message', sa.Column('mem0_memory_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'content')
    op.drop_column('chat_message', 'role')
    op.drop_column('chat_message', 'session_id')
    op.create_table('linked_provider',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('patient_fhir_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('linked_provider_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('linked_provider_pkey'))
    )
    # ### end Alembic commands ###
