"""updated tables

Revision ID: 226aac4b42b0
Revises: 40560b325462
Create Date: 2026-01-05 05:24:56.548313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '226aac4b42b0'
down_revision: Union[str, Sequence[str], None] = '40560b325462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthtrend', sa.Column('analysis_data', sa.JSON(), nullable=True))
    op.add_column('healthtrend', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('healthtrend_record_id_fkey'), 'healthtrend', type_='foreignkey')
    op.drop_column('healthtrend', 'analysis_date')
    op.drop_column('healthtrend', 'record_id')
    op.drop_column('healthtrend', 'event_dates')
    op.drop_column('healthtrend', 'trend_name')
    op.drop_column('healthtrend', 'is_major')
    op.drop_column('healthtrend', 'citation')
    op.drop_column('healthtrend', 'tip')
    op.drop_index(op.f('ix_medicalrecord_file_hash'), table_name='medicalrecord')
    op.drop_column('medicalrecord', 'file_size')
    op.drop_column('medicalrecord', 'file_hash')
    op.add_column('timelineevent', sa.Column('analysis_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('timelineevent', sa.Column('analysis_data', sa.JSON(), nullable=True))
    op.add_column('timelineevent', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('timelineevent_record_id_fkey'), 'timelineevent', type_='foreignkey')
    op.drop_column('timelineevent', 'title')
    op.drop_column('timelineevent', 'analysis_date')
    op.drop_column('timelineevent', 'record_id')
    op.drop_column('timelineevent', 'overall_summary')
    op.drop_column('timelineevent', 'is_major')
    op.drop_column('timelineevent', 'event_date')
    op.drop_column('timelineevent', 'citation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelineevent', sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('timelineevent', sa.Column('event_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('timelineevent', sa.Column('is_major', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('timelineevent', sa.Column('overall_summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('timelineevent', sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timelineevent', sa.Column('analysis_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('timelineevent', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('timelineevent_record_id_fkey'), 'timelineevent', 'medicalrecord', ['record_id'], ['id'])
    op.drop_column('timelineevent', 'updated_at')
    op.drop_column('timelineevent', 'analysis_data')
    op.drop_column('timelineevent', 'analysis_summary')
    op.add_column('medicalrecord', sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medicalrecord', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_medicalrecord_file_hash'), 'medicalrecord', ['file_hash'], unique=False)
    op.add_column('healthtrend', sa.Column('tip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('healthtrend', sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('healthtrend', sa.Column('is_major', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('healthtrend', sa.Column('trend_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('healthtrend', sa.Column('event_dates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('healthtrend', sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('healthtrend', sa.Column('analysis_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('healthtrend_record_id_fkey'), 'healthtrend', 'medicalrecord', ['record_id'], ['id'])
    op.drop_column('healthtrend', 'updated_at')
    op.drop_column('healthtrend', 'analysis_data')
    # ### end Alembic commands ###
