"""add_file_hash_and_size_to_medical_record

Revision ID: 2aff35904949
Revises: dd471bc1c73a
Create Date: 2026-01-04 19:29:42.128244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2aff35904949'
down_revision: Union[str, Sequence[str], None] = 'dd471bc1c73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalrecord', sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('medicalrecord', sa.Column('file_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_medicalrecord_file_hash'), 'medicalrecord', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicalrecord_file_hash'), table_name='medicalrecord')
    op.drop_column('medicalrecord', 'file_size')
    op.drop_column('medicalrecord', 'file_hash')
    # ### end Alembic commands ###
