"""update trend and timeline models

Revision ID: 40560b325462
Revises: 2aff35904949
Create Date: 2026-01-04 21:54:47.640202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40560b325462'
down_revision: Union[str, Sequence[str], None] = '2aff35904949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthtrend', sa.Column('analysis_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('healthtrend', sa.Column('trend_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('healthtrend', sa.Column('tip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('healthtrend', sa.Column('event_dates', sa.JSON(), nullable=True))
    op.add_column('healthtrend', sa.Column('trend_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('healthtrend', sa.Column('is_major', sa.Boolean(), nullable=False))
    op.add_column('healthtrend', sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('healthtrend', 'unit')
    op.drop_column('healthtrend', 'metric_name')
    op.drop_column('healthtrend', 'value')
    op.drop_column('healthtrend', 'recorded_at')
    op.add_column('timelineevent', sa.Column('analysis_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('timelineevent', sa.Column('overall_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('timelineevent', sa.Column('timeline_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('timelineevent', sa.Column('event_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('timelineevent', sa.Column('is_major', sa.Boolean(), nullable=False))
    op.add_column('timelineevent', sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('timelineevent', 'date')
    op.drop_column('timelineevent', 'category')
    op.drop_column('timelineevent', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelineevent', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('timelineevent', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('timelineevent', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('timelineevent', 'citation')
    op.drop_column('timelineevent', 'is_major')
    op.drop_column('timelineevent', 'event_date')
    op.drop_column('timelineevent', 'timeline_summary')
    op.drop_column('timelineevent', 'overall_summary')
    op.drop_column('timelineevent', 'analysis_date')
    op.add_column('healthtrend', sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('healthtrend', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('healthtrend', sa.Column('metric_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('healthtrend', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('healthtrend', 'citation')
    op.drop_column('healthtrend', 'is_major')
    op.drop_column('healthtrend', 'trend_name')
    op.drop_column('healthtrend', 'event_dates')
    op.drop_column('healthtrend', 'tip')
    op.drop_column('healthtrend', 'trend_summary')
    op.drop_column('healthtrend', 'analysis_date')
    # ### end Alembic commands ###
