"""Add Account and Verification tables for Better Auth

Revision ID: 7b46bbaa9dd1
Revises: 277f61155114
Create Date: 2025-12-27 06:06:12.121296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b46bbaa9dd1'
down_revision: Union[str, Sequence[str], None] = '277f61155114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accountId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('providerId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accessToken', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refreshToken', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accessTokenExpiresAt', sa.DateTime(), nullable=True),
    sa.Column('refreshTokenExpiresAt', sa.DateTime(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('verification')
    # ### end Alembic commands ###
