"""Add idToken to Account model

Revision ID: 9aa816929dcf
Revises: 7b46bbaa9dd1
Create Date: 2025-12-27 06:14:10.872472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9aa816929dcf'
down_revision: Union[str, Sequence[str], None] = '7b46bbaa9dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('idToken', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'idToken')
    # ### end Alembic commands ###
